### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by motohiro-mm** [motohiro-mm/GohanSummit#5]
エレベーターピッチ
https://bootcamp.fjord.jp/products/20181

ペーパープロトタイプ
https://bootcamp.fjord.jp/products/20557

リソース設計
https://github.com/motohiro-mm/MenuDiscussionBoard/issues/34

**Comment by motohiro-mm** [comment]
![Image](https://github.com/user-attachments/assets/a823588b-f325-4ff7-b4d2-6c2a5e2d3257)

### 補足
#### Userモデル

**Comment by motohiro-mm** [comment]
<img src="https://github.com/user-attachments/assets/2fc2125d-b3e0-4375-87a3-f2c67ccabb5d" width="70%">

**Comment by yuuu** [comment]
気になった点をコメントします。

- `Menus` はリソース設計を見る限り「献立表の共有画面」と解釈しましたが、これは `Menus`  というよりは `Groups` といった名前の方が適切に見えました
- `Menus` の所有者を表すリレーションが存在しないようです
    - 存在しなくても問題ないでしょうか？
- `Remark` は `Meal` ごとに区切られた相談部屋に投稿するものではなく、 `Menu` ごとに1つの部屋が作られるという理解であっていますか？
    - ペーパープロトタイプを見る限り、献立ごとに相談部屋が作られるのかなと想像していたので確認しています。

**Comment by motohiro-mm** [comment]
ご確認いただきありがとうございます！

> Menus はリソース設計を見る限り「献立表の共有画面」と解釈しましたが、これは Menus というよりは Groups といった名前の方が適切に見えました

Menusテーブルは、Mealsの集まり＝献立表、のつもりでした！
Menusテーブルには`invitation_token`をもたせています。`invitation_token`が含まれたURLから、招待された人が初回ログインすることでUserが作られるのと同時にそのMenu（献立表）に参加できる、といった流れを考えていました。
「献立表に属するユーザー」というのはたしかに変なので「グループに属するユーザー」のほうが良さそうに思えましたが、「ユーザーが共有している献立表」と考えるとMenu（献立表）でも良さそうに私としては思えました。
関連付けとしてはGroupsという名称のほうが適していますでしょうか？

> Menus の所有者を表すリレーションが存在しないようです。存在しなくても問題ないでしょうか？

所有者というのは、「オーナー」（Menuの作成者）という認識であってますでしょうか？

Userが招待URL以外から新規ログインしたときにUserとMenuを同時に新規作成する予定でいます。
Menuを作成したユーザーを削除する際、他にそのMenuをもっているユーザーがいる場合にはMenuは削除しないようにしたいです。
ユーザー削除時にそのMenuに属するユーザーがいるかを確認し、Menuに属するユーザーが0人になるときにユーザーとともにMenuを削除する形にしようと考えています。

ですので、Menuのオーナー・作成者のカラムは必要ないと考えました。

> Remark は Meal ごとに区切られた相談部屋に投稿するものではなく、 Menu ごとに1つの部屋が作られるという理解であっていますか？
ペーパープロトタイプを見る限り、献立ごとに相談部屋が作られるのかなと想像していたので確認しています。

Remarkは日付ごとに区切られた相談部屋に投稿するようにしたいです。
Mealはmeal_dateをもっているので、その意味では「Mealごとに区切られた」ということでもイコールかと思います。
最初は「MealごとのRemark」としてRemarkとMealを関連づけてRemarkに`meal_id`をもたせると`meal_date`も受け取れて良いと考えたのですが、そうするとRemarkを作成したいときに先にMealがないといけないのではないかと思いました。
献立を相談するためのRemarkを作成するために、先にDishをもたないMealを全日付分作成しておく必要がある、というのは無駄ではないのか？と思ったので、現状RemarkはMealには関連づけず独自で`meal_date`をもち、MealはDishを作成するときに一緒に作成する想定をしています。
どうするのが適しているのか悩んでいる部分なので、ぜひアドバイスいただきたいです。

**Comment by yuuu** [comment]
コメントありがとうございます。
もしかすると、自分がまだ意図を100%汲み取れていないかもしれませんが、頂いたコメントを読んで気になった点をコメントしますね 🙏 

### テーブルの名称について

- 日本語で「献立」「メニュー」という単語を聞くと、「(1食)の献立・メニュー」を想像してしまうので、そこが違和感の原因な気がしています。
    - 今「メニュー」と呼んでいるものは実際にはメニューが集まり・共有する場のようなイメージなので、それを表す単語をチョイスした方が良さそうです。
    - Groupは抽象的過ぎるので、もう少しだけ具体化した名前があると良いのですが...
- 「Meal」も懸念に挙げていただいているとおり、1レコード＝1食という想像をしてしまいますね。
    - このテーブルの1レコード＝1日の食事の計画なので「MealPlan」といった名前にするとどうでしょう？
- 「Dishes」がむしろ「Menu」もしくは「Meal」になるとしっくりきそうです。

### Menusの所有者について

- 新規ログインしたときに同時に新規作成する旨は理解できました。
- 誰もいなくなったときに削除の旨も承知です。

### Remarkはどの単位で作成するのか

> 日付ごとに区切られた相談部屋

仕様に登場する可算名詞をテーブルにするという考え方に則ると、「相談部屋」というテーブルが必要なのかなと感じました。

今は相談部屋が日付単位なので、「相談部屋」テーブルがなくても成立しそうに見えますが、今後「1日に複数の相談部屋を設けられるようにする」「日付とは別の単位で相談部屋を設置できるようにする」といった仕様変更が発生すると設計が破綻しそうです。

相談部屋の作成タイミングはリンクをクリックしたときでも良いですし、明示的に新規登録画面を設けても良いと思っています。

**Comment by motohiro-mm** [comment]
ご確認いただきありがとうございます！
前回のコメントをふまえてER図を修正していますのでご確認ください。
https://github.com/motohiro-mm/GohanSummit/issues/5#issuecomment-2343558463
コメントの返信、および質問を以下でさせていただきます。

## テーブルの名称について
### Menusテーブル
> 日本語で「献立」「メニュー」という単語を聞くと、「(1食)の献立・メニュー」を想像してしまうので、そこが違和感の原因な気がしています。

なるほど、そこで違和感を感じられていたのですね。

私も最初はそのように思っていたのですが、献立・メニューなどの英単語を調べていくうちに例文などでのmenuの使われ方が気になり最終的に[このサイト](https://cuisine-kingdom.com/menu/)の説明をみました。
それを踏まえてmenuという英単語を献立表として扱う形にしていました。

ただサービスを使うのは我々（私）なので、自分がピンとくる単語の方が良さそうですね！

> 今「メニュー」と呼んでいるものは実際にはメニューが集まり・共有する場のようなイメージなので、それを表す単語をチョイスした方が良さそうです。Groupは抽象的過ぎるので、もう少しだけ具体化した名前があると良いのですが...

献立表を共有するグループは、私のイメージでは家族を想定しています。
ですので、Groupをもう少し具体的にしてFamilyとかはどうでしょうか？
家族以外で献立表を共有する可能性もなくはないかもしれませんが…

### Mealsテーブル、Dishesテーブル
> 「Meal」も懸念に挙げていただいているとおり、1レコード＝1食という想像をしてしまいますね。
このテーブルの1レコード＝1日の食事の計画なので「MealPlan」といった名前にするとどうでしょう？

「MealPlan」、「Meal」がしっくりきたのでそのように修正しました！
アドバイスありがとうございます🙏

## 相談部屋について
> 今は相談部屋が日付単位なので、「相談部屋」テーブルがなくても成立しそうに見えますが、今後「1日に複数の相談部屋を設けられるようにする」「日付とは別の単位で相談部屋を設置できるようにする」といった仕様変更が発生すると設計が破綻しそうです。

なるほど、このサービスは相談部屋は日付単位で作成する仕様でしか考えていなかったので、そのような視点は思いついていませんでした。
RemarksテーブルとFamiliesテーブルの間に、相談部屋用のテーブル＝MeetingRoomsテーブルを作成してみました。
現状では、MeetingRoomsテーブルとMealPlansテーブルのカラムは全部同じものになってしまっていますが、上記のような仕様変更の可能性を考慮すると、カラムが全て同じテーブルが2種類あっても問題ない、という理解で合っていますでしょうか？

**Comment by yuuu** [comment]
@motohiro-mm 
検討ありがとうございます 👍 自分が抱いていた違和感はかなり解消されました。
2点コメントしますが、これは修正マストではないので、参考まで。

- `Family` というテーブル名、自分も最初に思いついた候補の1つでした。 `Family` を提案しなかった理由としては、献立を相談する相手が家族と言い切れるのか(もしかしたら本当の家族ではなくルームシェアしている相手とか...)を想像して、抽象度を上げた `Group` を提案していました
    - ルームシェアしている相手も広義の「家族」ですし、献立を相談するということは同じ釜の飯を食っている状態なので、「家族」としてしまうのが一番しっくりきますね。
- `MealPlans` と `MeetingRooms` の間に関連は不要でしょうか？
    - 例えば「この献立を決めるまでの相談内容を見たい」といったシチュエーションで、今の設計だと同じ `date` のレコードを探すしか手がないです
    - 「相談部屋は1日に1つ」という仕様が崩れるとこの方法は使えなくなってしまうので、この2つの間のテーブルにリレーションがあったほうが良いかも？と思いました

**Comment by motohiro-mm** [comment]
違和感が大方解消されたとのことでよかったです！
ありがとうございます！
ER図再度修正しました！
https://github.com/motohiro-mm/GohanSummit/issues/5#issuecomment-2343558463

## Familyについて
>  Family を提案しなかった理由としては、献立を相談する相手が家族と言い切れるのか(もしかしたら本当の家族ではなくルームシェアしている相手とか...)を想像して、抽象度を上げた Group を提案していました

色々考えてくださりありがとうございます🙏
家族以外だと「仲間」なども考えましたが、あまりピンとくる英単語は見つけられませんでした。

> 献立を相談するということは同じ釜の飯を食っている状態なので、「家族」としてしまうのが一番しっくりきますね。

なるほど！！！！
同じ釜の飯を食う＝戸籍とか関係なく「家族」ということですね！腹落ちしましたしとても良い考え方だと思いました！
ですのでこのままFamiliesテーブルで進めようと思います！
ありがとうございます！

## MealPlansテーブルとMeetingRoomsテーブルの関連付け
挙げていただいた2つの理由は、たしかにその通りだと思いました！
関連付けはあった方が良いと思いましたので、追加しました。

**Comment by yuuu** [comment]
@motohiro-mm 
修正ありがとうございます 👍 
MealPlansテーブルとMeetingRoomsテーブルの関連付けについて、この2つのテーブルの関係は1:1, 1:N, N:1, N:Nのどれでしょうか？

自分の認識だとMealPlans:MeetingRooms=1:1もしくはN:1だと思っていました。というのも以前のコメントで「先に `MeetingRooms ` で議論をしてから `MealPlans ` を作成する」と聞いていたためです。そう考えると、今のリレーションは逆、といったことはないでしょうか？

**Comment by yuuu** [comment]
リソース設計の方を見ていて気づきましたが、

1. MealPlansは先に作っておく
2. MeetingRoomsで相談する
3. 相談結果を踏まえてMealsを決める

という順番なのかもしれませんね。そうであればリレーションに関しては今のER図で問題なさそうです！

----

今のER図で進める場合、 `MeetingRooms` の `meal_date` は親の `MealPlans` が持っているので不要そうと思いました。

**Comment by motohiro-mm** [comment]
MeetingRoomsの`meal_date`をなくすよう修正しました！
https://github.com/motohiro-mm/GohanSummit/issues/5#issuecomment-2343558463

MealPlansテーブルとMeetingRoomsテーブルの関連付けは、「MealPlans:MeetingRooms=1:N 」で考えています。
この関連付けにした理由を、私が思う仕様のイメージも交えて説明させてください🙏

私がこのサービスに求める仕様が大きく2つあります。
1. 相談部屋で家族で献立を相談しそれを直接献立表に登録できる
これはyuuuさんがコメントしてくださった1→2→3の順番で実装していければと思っています。
相談部屋で出た提案（Meal1つ分）に対し朝昼夜のタイミングを入れて決定を押すだけでその日の献立に登録できるようにしたいです。

2. 相談部屋を介せず、献立を直接献立表に登録できる
なぜこの機能が必要かと言うと夫と直接対面で献立の相談ができた場合、相談部屋を使う必要がなくなるからです。
（現状献立の相談を行なっているのはLINEもしくは直接対面でその時々のタイミングでまちまちです）
献立表を外出先などでも確認したいので、対面で献立を決めた時も献立表への登録はしたいのでこの仕様が必要です。

この2つを実装したいので、献立表一覧画面では各日付ごとに「相談部屋」と「直接登録」の2つのリンクを配置したいと考えています。
<img src="https://github.com/user-attachments/assets/b46ed40b-3373-482a-9d9e-3391364296eb" width="30%">

MeetingRoomを使わない可能性もあるので、「MealPlans:MeetingRooms=1:1もしくはN:1 」ではなく「MealPlans:MeetingRooms=1:N 」で考えていました。

自分の欲しい仕様は上記なのですが分かりづらいのと、自分の欲しい仕様がこのER図で合っているかの不安や理解不足はあるので、気になるところがあればどんどんご指摘いただければ幸いです！

**Comment by yuuu** [comment]
@motohiro-mm 
修正内容について確認しました 👍 設計意図は理解できましたが1点だけ確認させてください。

> MealPlans:MeetingRooms=1:N

とのことですが、 `1:1` ではなく `1:N` でしょうか？
もし `1:N` の場合、相談部屋が複数作られるシチュエーションにはどういったものがありそうでしょうか？

**Comment by motohiro-mm** [comment]
現状ではMealPlans:MeetingRooms=1:1ですが、仕様変更の可能性を考慮してMealPlans:MeetingRooms=1:Nとしました！
ですので現状の仕様で相談部屋が複数作られるシチュエーションは考えていません。

仕様変更がもし今後起こった場合に、テーブルの追加は大変だからMeetingRoomsテーブルを先に作っておいた方が良いけれども、関連付けの変更はあとからできるので今は現状に合わせた1:1にすべき、ということであれば修正します！
（そのあたりの加減があまり分かっていなくすみません🙏）

**Comment by yuuu** [comment]
@motohiro-mm 
なるほど承知です 👍 1:1でも1:Nでも実際のDBスキーマは同じになるはずですので、認識が合っていることが確認できれば、このままで問題ありません。

**Comment by motohiro-mm** [comment]
@yuuu 

> 1:1でも1:Nでも実際のDBスキーマは同じになるはずですので、認識が合っていることが確認できれば、このままで問題ありません。

たしかに！スキーマファイルでは一緒ですね🙏

たくさんご指導いただきありがとうございました！😄
